### ISSUE TITLE
Exercise 2 - Interactive Program

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/advanced_ruby_track#2]
https://github.com/segunadeleye/advanced_ruby_track/blob/master/interactive_program/lib/interactive_program.rb
https://github.com/segunadeleye/advanced_ruby_track/blob/master/interactive_program/bin/main.rb

Write a program interactively, through the command line 
Enter a blank line to evaluate. 
Enter `q` to quit.

**Comment by yuktikhurana** [comment]
issue is it doesn't store the variables. it should behave  like irb.
for example
i did
>> a = 2
>> b = 4
>>
>> c = a + b
i get an exception. it can't find a.
Can we fix this?

**Comment by segunadeleye** [comment]
# Fixed!!!

**Comment by yuktikhurana** [comment]
looks good
