### ISSUE TITLE
Exercise 3: Program from Command Line

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/advanced_ruby_track#3]
https://github.com/segunadeleye/advanced_ruby_track/blob/master/method_creator/lib/method_creator.rb
https://github.com/segunadeleye/advanced_ruby_track/blob/master/method_creator/bin/main.rb

Prompt the user for a method name and a single line of code; then actually define the method and call it

**Comment by yuktikhurana** [comment]
1. https://github.com/segunadeleye/advanced_ruby_track/blob/master/method_creator/lib/method_creator.rb#L11 can we do it without eval?
2. how can we see the result of the method call ?

**Comment by segunadeleye** [comment]
Fixed

**Comment by yuktikhurana** [comment]
looks fine
