### ISSUE TITLE
Exercise 4: Shopping List

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/advanced_ruby_track#4]
https://github.com/segunadeleye/advanced_ruby_track/blob/master/shopping_list/lib/shopping_list.rb
https://github.com/segunadeleye/advanced_ruby_track/blob/master/shopping_list/bin/main.rb

Write a simple DSL for creating a shopping list. We should be able to specify the item name and quantity. Something like.
`sl = ShoppingList.new`
`sl.items do`
`add("Toothpaste",2)`
`add("Computer",1)`
`end`

**Comment by Shruti2791** [comment]
Looks good :+1:
