### ISSUE TITLE
Exercise 5: Singleton Method

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/advanced_ruby_track#5]
https://github.com/segunadeleye/advanced_ruby_track/blob/master/singleton_method/lib/string.rb
https://github.com/segunadeleye/advanced_ruby_track/blob/master/singleton_method/bin/main.rb

Create an instance of a class string.Define a method on this instance in a way that it is available only on this instance. If you create another instance of the class and try to call this method, it should give a method not defined error.Create this method using
`def something.method_name` and also `class << self`

**Comment by abhishekjain16** [comment]
List down all the methods for creating singleton method.

**Comment by segunadeleye** [comment]
Fixed.
