### ISSUE TITLE
Exercise 7: Creating Classes from CSV

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/advanced_ruby_track#7]
https://github.com/segunadeleye/advanced_ruby_track/blob/master/create_class_from_csv/lib/class_creator.rb
https://github.com/segunadeleye/advanced_ruby_track/blob/master/create_class_from_csv/bin/main.rb

Read a csv format file and construct a new class with the name of the file dynamically. So if the csv is persons.csv, the ruby class should be person, if it's places.csv, the ruby class should be places. Also create methods for reading and displaying each value in "csv" file and values in first row of csv file will act as name of the function. Construct an array of objects and associate each object with the row of a csv file. For example the content of the csv file could be
`name,age,city`
`gaurav,23,karnal`
`vilok,23,hissar`

**Comment by mkangia** [comment]
1) please handle the case if file is missing
2) You can also use/overwrite the to_s method on class for pretty display

**Comment by segunadeleye** [comment]
Fixed.
